image: "golang:1.13"

before_script:
  - mkdir -p /go/src/github.com/katzenpost
  - cp -r /builds/katzenpost/* /go/src/github.com/katzenpost/
  - cd /go/src/github.com/katzenpost/panda
  - go get -v -t ./...

test-panda:
  script:
    - go test -v -cover -race ./...
