
[[constraint]]
  name = "github.com/katzenpost/client"
  version = "0.0.1"

[[constraint]]
  name = "github.com/katzenpost/core"
  version = "0.0.7"

[[constraint]]
  name = "github.com/katzenpost/server"
  version = "0.0.7"

[[constraint]]
  name = "github.com/op/go-logging"
  version = "1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/ugorji/go"
  version = "1.1.4"

[prune]
  go-tests = true
  unused-packages = true
