
[UpstreamProxy]
  Type = "none"

[Logging]
  Disable = false
  Level = "DEBUG"

#[NonvotingAuthority]
#    Address = "127.0.0.1:29483"
#    PublicKey = "o4w1Nyj/nKNwho5SWfAIfh7SMU8FRx52nMHGgYsMHqQ="

[VotingAuthority]
[[VotingAuthority.Peers]]
   IdentityPublicKey = "xCjlBac+wanLeUQbrNLTwQzFKIwfJqpoKZYfB/hvZHo="
   LinkPublicKey = "I49V1w7OJ/Kcw7YbEvo+92akE9cYLGeXRBg6KE/sYS8="
   Addresses = ["172.28.1.10:21483"]

[[VotingAuthority.Peers]]
   IdentityPublicKey = "OAfHeF/U+y7dXWgxSCuPOBIqgBOuIC7JKilZJU/Dt9c="
   LinkPublicKey = "fZcGD+uPm18BYuDKXS3eozp9+i2hW2SWgnuapP0ftgE="
   Addresses = ["172.28.1.8:22483"]

[[VotingAuthority.Peers]]
   IdentityPublicKey = "e8iJCBjepa/Cpmmu5UCcR6BZgYssUTaih9U01ysEK+o="
   LinkPublicKey = "jBVovebgazZB38Q3OZzEvLb8UDEUB6sRQZAULDrxKAY="
   Addresses = ["172.28.1.9:23483"]

[Debug]
  PollingInterval = 10
  